# Generated by Django 4.2.8 on 2024-01-04 12:38

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FrendshipRequest',
            new_name='FriendshipRequest',
        ),
    ]
