# Generated by Django 4.2.8 on 2024-01-04 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_rename_frendshiprequest_friendshiprequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friendshiprequest',
            name='response',
            field=models.CharField(choices=[('ACCEPT', 'Accept'), ('REJECT', 'Reject')], default='NONE', max_length=10),
        ),
    ]
